#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#
# Any extra variables not found in the original file have been ignored.
#

module "req" {
  source = "module-req"

  bucket_name                    = "${var.customer}-terraform-remote-state"
  codecommit_key_public          = ""
  codecommit_readonly_key_public = ""
  codecommit_repository_name     = "cycloid-${var.customer}-servicescatalog"
  create_codecommit_repository   = 1
  create_s3_bucket               = 1
  customer                       = var.customer
  env                            = var.env
  force_destroy                  = true
  infra_iam_arn                  = ""
  project                        = var.project
  suffix                         = ""
}

